# This file was generated by GoReleaser. DO NOT EDIT.
class Lsec2 < Formula
  desc "List view of aws ec2 instances"
  homepage "https://github.com/goldeneggg/lsec2"
  version "0.2.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/goldeneggg/lsec2/releases/download/v0.2.10/lsec2_0.2.10_darwin_amd64.tar.gz"
    sha256 "dcec85bd187cb573236416e2aad6bf0716c9f2b48d0ddcb6dd24950e03cee562"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/goldeneggg/lsec2/releases/download/v0.2.10/lsec2_0.2.10_linux_amd64.tar.gz"
      sha256 "85e114b1f9372deb0a982ed135a77b873c0f4a74e9ab3aa15ef31a89f60f9b27"
    end
  end

  def install
    bin.install "lsec2"
  end

  test do
    system '#{bin}/lsec2 -v'
  end
end
